//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASIENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASIENTO()
        {
            this.DISPONIBILIDAD = new HashSet<DISPONIBILIDAD>();
        }
    
        public int ID_ASIENTO { get; set; }
        public string COD_CLASE { get; set; }
        public Nullable<int> NUMERO { get; set; }
        public string LETRA { get; set; }
    
        public virtual TIPO_CLASE TIPO_CLASE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISPONIBILIDAD> DISPONIBILIDAD { get; set; }
    }
}
