//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AVION()
        {
            this.GETAWEY = new HashSet<GETAWEY>();
            this.VUELO = new HashSet<VUELO>();
        }
    
        public string PLACA_AVION { get; set; }
        public Nullable<int> ID_TIPO { get; set; }
        public string COD_MARCA { get; set; }
        public Nullable<int> CAPACIDAD_ASIENTO { get; set; }
        public string COD_LA { get; set; }
        public Nullable<bool> ESTADO_AVION { get; set; }
    
        public virtual LINEA_AEREA LINEA_AEREA { get; set; }
        public virtual MARCA_AVION MARCA_AVION { get; set; }
        public virtual TIPO_AVION TIPO_AVION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GETAWEY> GETAWEY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VUELO> VUELO { get; set; }
    }
}
