//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_NATURAL
    {
        public int ID_NATURAL { get; set; }
        public int ID_Persona { get; set; }
        public Nullable<int> ID_TIPO_DOCUMENTO { get; set; }
        public string NUM_DOCUMETO { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public Nullable<int> ID_GENERO { get; set; }
        public string ESTADO_CIVIL { get; set; }
        public Nullable<int> NUM_MILLAS { get; set; }
        public string NUM_VIAJERO_FREC { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual GENERO GENERO { get; set; }
        public virtual TIPO_DOCUMENTO TIPO_DOCUMENTO { get; set; }
    }
}
