//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_EMPRESARIAL
    {
        public int ID_EMPRESARIAL { get; set; }
        public int ID_Persona { get; set; }
        public string NOM_EMPRESA { get; set; }
        public string NIT { get; set; }
        public string NIC { get; set; }
        public Nullable<int> NUM_MILLAS { get; set; }
        public string NUM_VIAJERO_FREC { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
