//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SAVEntities : DbContext
    {
        public SAVEntities()
            : base("name=SAVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AEROPUERTO> AEROPUERTO { get; set; }
        public virtual DbSet<ASIENTO> ASIENTO { get; set; }
        public virtual DbSet<AVION> AVION { get; set; }
        public virtual DbSet<CIUDAD> CIUDAD { get; set; }
        public virtual DbSet<CLIENTE_EMPRESARIAL> CLIENTE_EMPRESARIAL { get; set; }
        public virtual DbSet<CLIENTE_NATURAL> CLIENTE_NATURAL { get; set; }
        public virtual DbSet<DISPONIBILIDAD> DISPONIBILIDAD { get; set; }
        public virtual DbSet<GENERO> GENERO { get; set; }
        public virtual DbSet<GETAWEY> GETAWEY { get; set; }
        public virtual DbSet<ITINERARIO> ITINERARIO { get; set; }
        public virtual DbSet<LINEA_AEREA> LINEA_AEREA { get; set; }
        public virtual DbSet<MALETA_EXTRA> MALETA_EXTRA { get; set; }
        public virtual DbSet<MARCA_AVION> MARCA_AVION { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<PAIS> PAIS { get; set; }
        public virtual DbSet<PASAJERO> PASAJERO { get; set; }
        public virtual DbSet<Permission> Permission { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<REGION> REGION { get; set; }
        public virtual DbSet<REGISTRO_PAGO> REGISTRO_PAGO { get; set; }
        public virtual DbSet<RESERVACION> RESERVACION { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<SUBREGION> SUBREGION { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TICKETS> TICKETS { get; set; }
        public virtual DbSet<TIPO_AVION> TIPO_AVION { get; set; }
        public virtual DbSet<TIPO_CLASE> TIPO_CLASE { get; set; }
        public virtual DbSet<TIPO_DOCUMENTO> TIPO_DOCUMENTO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<VUELO> VUELO { get; set; }
        public virtual DbSet<MenuTemp> MenuTemp { get; set; }
    }
}
