//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISPONIBILIDAD
    {
        public int ID_DISPONIBLE { get; set; }
        public string COD_VUELO { get; set; }
        public Nullable<int> ID_ASIENTOS { get; set; }
        public Nullable<bool> DISPONIBLE { get; set; }
    
        public virtual ASIENTO ASIENTO { get; set; }
        public virtual VUELO VUELO { get; set; }
    }
}
