//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITINERARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITINERARIO()
        {
            this.VUELO = new HashSet<VUELO>();
        }
    
        public int ID_ITINERARIO { get; set; }
        public string ORIGEN { get; set; }
        public string DESTINO { get; set; }
        public Nullable<System.TimeSpan> HORA_SALIDA { get; set; }
        public Nullable<System.TimeSpan> HORA_LLEGADA { get; set; }
    
        public virtual AEROPUERTO AEROPUERTO { get; set; }
        public virtual AEROPUERTO AEROPUERTO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VUELO> VUELO { get; set; }
    }
}
