//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINEA_AEREA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LINEA_AEREA()
        {
            this.AVION = new HashSet<AVION>();
            this.GETAWEY = new HashSet<GETAWEY>();
            this.VUELO = new HashSet<VUELO>();
        }
    
        public string COD_LINEA_AEREA { get; set; }
        public string COD_AEROPUERTO { get; set; }
        public string NOM_OFICIAL { get; set; }
        public string NOM_CORTO { get; set; }
        public string NOM_REPRESENTANTE { get; set; }
        public string COD_PAIS { get; set; }
        public string URL { get; set; }
        public string FACEBOOK { get; set; }
        public string TWITTER { get; set; }
        public string INSTAGRAM { get; set; }
        public string YOUTUBE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> FECHA_FUNDACION { get; set; }
        public Nullable<bool> ESTADO_LA { get; set; }
    
        public virtual AEROPUERTO AEROPUERTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVION> AVION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GETAWEY> GETAWEY { get; set; }
        public virtual PAIS PAIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VUELO> VUELO { get; set; }
    }
}
