//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASAJERO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PASAJERO()
        {
            this.TICKETS = new HashSet<TICKETS>();
        }
    
        public int ID_PASAJERO { get; set; }
        public string PRIMER_NOM_P { get; set; }
        public string SEGUNDO_NOM_P { get; set; }
        public string PRIMERO_APELLIDO_P { get; set; }
        public string SEGUNDO_APELLIDO_P { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public string TIPO_DOC { get; set; }
        public string NUM_DOC { get; set; }
        public string GENERO { get; set; }
        public Nullable<int> CANTIDAD_MALETA { get; set; }
    
        public virtual Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKETS> TICKETS { get; set; }
    }
}
