//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.CLIENTE_EMPRESARIAL = new HashSet<CLIENTE_EMPRESARIAL>();
            this.CLIENTE_NATURAL = new HashSet<CLIENTE_NATURAL>();
            this.PASAJERO = new HashSet<PASAJERO>();
        }
    
        public int ID_Persona { get; set; }
        public string PRIMER_NOM { get; set; }
        public string SEGUNDO_NOM { get; set; }
        public string PRIMER_APELLIDO { get; set; }
        public string SEGUNDO_APELLIDO { get; set; }
        public string TEL_FIJO { get; set; }
        public string TEL_MOVIL { get; set; }
        public string DIRECCION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_EMPRESARIAL> CLIENTE_EMPRESARIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE_NATURAL> CLIENTE_NATURAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PASAJERO> PASAJERO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
