//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VUELO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VUELO()
        {
            this.DISPONIBILIDAD1 = new HashSet<DISPONIBILIDAD>();
            this.RESERVACION = new HashSet<RESERVACION>();
        }
    
        public string COD_VUELO { get; set; }
        public string COD_LINEA_AEREA { get; set; }
        public Nullable<double> MILLAS_REALES { get; set; }
        public Nullable<int> MILLAS_OTROGADAS { get; set; }
        public string PLACA_AVION { get; set; }
        public Nullable<int> ID_ITINERARIO { get; set; }
        public Nullable<System.DateTime> FECHA_SALIDA { get; set; }
        public Nullable<int> DISPONIBILIDAD { get; set; }
    
        public virtual AVION AVION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISPONIBILIDAD> DISPONIBILIDAD1 { get; set; }
        public virtual ITINERARIO ITINERARIO { get; set; }
        public virtual LINEA_AEREA LINEA_AEREA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVACION> RESERVACION { get; set; }
    }
}
