//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISPONIBILIDAD_CLASE
    {
        public int ID_DISP_CLASE { get; set; }
        public string COD_CLASE { get; set; }
        public Nullable<int> CANTIDAD_DISPONIBLE { get; set; }
    
        public virtual TIPO_CLASE TIPO_CLASE { get; set; }
    }
}
