//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HORARIO_VUELO
    {
        public int ID_HORARIO { get; set; }
        public string PLACA_AVION { get; set; }
        public int ID_ITINERARIO { get; set; }
        public Nullable<int> COD_VUELO { get; set; }
        public Nullable<System.DateTime> FECHA_VUELO { get; set; }
        public Nullable<System.TimeSpan> HORA_VUELO { get; set; }
    }
}
