//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITINERARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITINERARIO()
        {
            this.VUELO = new HashSet<VUELO>();
        }
    
        public int ID_ITINERARIO { get; set; }
        public int COD_RESERVACION { get; set; }
        public Nullable<int> ID_TICKET { get; set; }
        public Nullable<int> ID_HORARIO { get; set; }
        public Nullable<int> id_O_D { get; set; }
    
        public virtual HORARIOS HORARIOS { get; set; }
        public virtual ORIGENDESTINO ORIGENDESTINO { get; set; }
        public virtual TICKETS TICKETS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VUELO> VUELO { get; set; }
    }
}
