//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int PermissionID { get; set; }
        public string RoleID { get; set; }
        public int MenuID { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual ROL ROL { get; set; }
    }
}
