//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKETS
    {
        public int ID_TICKET { get; set; }
        public Nullable<int> ID_ITINERARIO { get; set; }
        public int ID_PASAJERO { get; set; }
        public Nullable<int> NUM_ASIENTO { get; set; }
        public string COD_CLASE { get; set; }
    
        public virtual ITINERARIO ITINERARIO { get; set; }
        public virtual PASAJERO PASAJERO { get; set; }
        public virtual TIPO_CLASE TIPO_CLASE { get; set; }
    }
}
