//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_CLASE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_CLASE()
        {
            this.AVION = new HashSet<AVION>();
            this.DISPONIBILIDAD_CLASE = new HashSet<DISPONIBILIDAD_CLASE>();
            this.REGISTRO_PAGO = new HashSet<REGISTRO_PAGO>();
            this.TICKETS = new HashSet<TICKETS>();
        }
    
        public string COD_CLASE { get; set; }
        public Nullable<int> ID_ASIENTO { get; set; }
        public Nullable<int> ID_PAGO { get; set; }
        public string NOM_CLASE { get; set; }
        public Nullable<double> MARGEN_UTILIDAD { get; set; }
        public Nullable<int> CANTIDAD_ASIENTOS { get; set; }
        public Nullable<int> ID_TICKET { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVION> AVION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISPONIBILIDAD_CLASE> DISPONIBILIDAD_CLASE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_PAGO> REGISTRO_PAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKETS> TICKETS { get; set; }
    }
}
