//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int ID_USUARIO { get; set; }
        public string COD_ROL { get; set; }
        public string Email { get; set; }
        public string CONTASENA { get; set; }
        public Nullable<bool> ESTADO { get; set; }
        public string ReseteoContraCode { get; set; }
        public Nullable<System.Guid> ActivationCode { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual ROL ROL { get; set; }
    }
}
